name: Testing Github Actions

on:
  push: 
    branches: 
      - "master"

jobs:
  test-build:
    runs-on: windows

    steps:
      - uses: Mikael-RnD/setup-uipath@v2
        with:
          version: 24.12.9111.31003
