name: Testing Github Actions

on:
  push: 
    branches: 
      - "main"

jobs:
  test-build:
    runs-on: windows-latest

    steps:
      - uses: Mikael-RnD/setup-uipath@v2
        with:
          version: 24.12.9111.31003

      - name : Get the uipath cli version
        run : uipcli --version
        
      - name : Get the dotnet version
        run : dotnet --version
        
